<?php

/**
 * @file
 * This module provides Stripe (http://stripe.com/) payment gateway integration
 * to Commerce. Commerce Stripe offers a PCI-compliant way to process payments
 * straight from you Commerce shop.
 */

define('STRIPE_PUBLIC_KEY', '');
define('STRIPE_SECRET_KEY', '');

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_stripe_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['commerce_stripe'] = array(
    'title' => t('Stripe'),
    'description' => t('Stripe payment gateway'),
    'active' => TRUE,
    'terminal' => FALSE,
    'offsite' => FALSE,
    'callbacks' => array(
      'settings_form' => 'commerce_stripe_settings_form',
    ),
  );

  return $payment_methods;
}

/**
 * Payment method settings form.
 *
 * @param <type> $settings
 *   Default settings provided from rules
 *
 * @return <array>
 *   settings form array
 */
function commerce_stripe_settings_form($settings) {
  $form = array();
  $form['public_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Publishable Key'),
    '#description' => t('Publishable API Key. Get your key from https://stripe.com/'),
    '#default_value' => !empty($settings['public_key']) ? $settings['public_key'] : STRIPE_PUBLIC_KEY,
  );
  $form['secret_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Secret Key'),
    '#description' => t('Secret API Key. Get your key from https://stripe.com/'),
    '#default_value' => !empty($settings['secret_key']) ? $settings['secret_key'] : STRIPE_SECRET_KEY,
  );

  return $form;
}

/**
 * Payment method callback: checkout form.
 */
function commerce_stripe_submit_form($payment_method, $pane_values, $checkout_pane, $order) {

  module_load_include('inc', 'commerce_payment', 'includes/commerce_payment.credit_card');
  $form = commerce_payment_credit_card_form(array('number' => '', 'exp_month' => '', 'exp_year' => '', 'code' => ''));

  // To display validation errors.
  $form['total'] = array(
    '#type' => 'hidden',
    '#value' => $order->commerce_order_total['und'][0]['amount'],
    '#attributes' => array(
      'name' => '',
      'class' => array('stripe-order-total'),
    ),
  );

  // Load external libraries.
  $form['#attached']['js'] = array(
    'https://js.stripe.com/v1/',
    drupal_get_path('module', 'commerce_stripe') . '/commerce_stripe.js',
  );

  // And set our key.
  $form['set_stripe_key'] = array(
    '#type' => 'markup',
    '#markup' => '<script>jQuery(document).ready(function () { Stripe.setPublishableKey("' . _commerce_stripe_get_setting('public_key') . '"); });</script>',
  );

  // To display validation errors.
  $form['errors'] = array(
    '#type' => 'markup',
    '#markup' => "<div class='payment-errors'></div>",
  );

  return $form;
}

/**
 * Payment method callback: checkout form submission.
 */
function commerce_stripe_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {

  // Require needed Stripe library.
  require_once libraries_get_path('stripe-php') . '/lib/Stripe.php';

  // Set stripe secret key.
  Stripe::setApiKey(_commerce_stripe_get_setting('secret_key'));

  // Assemble charge parameters. Only 'usd' is supported.
  $c = array(
    'amount' => $charge['amount'],
    'currency' => 'usd',
    'card' => $_POST['stripeToken'],
    'description' => 'Order Number: ' . $order->order_number,
  );

  try{
    $response = Stripe_Charge::create($c);
  } catch (Exception $e) {
    drupal_set_message(t('We received the following error processing your card. Please enter you information again or try a different card.'), 'error');
    drupal_set_message(check_plain($e->getMessage()), 'error');
    watchdog('commerce_stripe', 'Following error received when processing card @stripe_error.', array('@stripe_error' => check_plain($e->getMessage())), WATCHDOG_NOTICE);
    return FALSE;
  }

  // Prepare a transaction object to represent the transaction attempt.
  $transaction = commerce_payment_transaction_new('commerce_stripe', $order->order_id);

  if ($response->paid) {
    $transaction->instance_id = $payment_method['instance_id'];
    $transaction->remote_id = $response->id;
    $transaction->amount = $charge['amount'];
    $transaction->currency_code = $charge['currency_code'];
    $transaction->payload[REQUEST_TIME] = $response;
    $transaction->message = "Payment completed successfully.";
    $transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;
  }
  else {
    drupal_set_message(t('We received the following error processing your card. Please enter you information again or try a different card.'), 'error');
    drupal_set_message(check_plain($response->card), 'error');
    watchdog('commerce_stripe', 'Following error received when processing card @stripe_error.', array('@stripe_error' => check_plain($response->card)), WATCHDOG_NOTICE);
    return FALSE;
  }

  // Save the transaction information.
  commerce_payment_transaction_save($transaction);
}

/**
 * Return payment method settings
 *
 * @param <type> $setting_name
 *   A string containing the setting name we are getting
 *
 * @return <string>
 *   setting value
 */
function _commerce_stripe_get_setting($setting_name) {
  $payment_method = commerce_payment_method_instance_load('commerce_stripe|commerce_payment_commerce_stripe');

  switch ($setting_name) {
    // Secret key.
    case 'secret_key':
      $setting = !empty($payment_method['settings']['secret_key']) ? $payment_method['settings']['secret_key'] : STRIPE_SECRET_KEY;
      break;
    // Publishable key.
    case 'public_key':
      $setting = !empty($payment_method['settings']['public_key']) ? $payment_method['settings']['public_key'] : STRIPE_PUBLIC_KEY;
      break;
  }
  return $setting;
}
